server:
  persistentVolume:
    enabled: false # Disabled for local demo purposes
  service:
    type: NodePort

alertmanager:
  enabled: false

pushgateway:
  enabled: false

# Scrape configuration for our app
extraScrapeConfigs: |
  - job_name: 'k8s-cicd-demo-app'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
        action: keep
        regex: web-app
      - source_labels: [__meta_kubernetes_pod_container_port_number]
        action: keep
        regex: 3000
