CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  phone TEXT UNIQUE,
  role TEXT DEFAULT 'user',
  avatar_url TEXT,
  location JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  description TEXT,
  icon_name TEXT
);

CREATE TABLE IF NOT EXISTS providers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  service_id BIGINT REFERENCES services(id),
  rating FLOAT DEFAULT 0.0,
  base_price FLOAT,
  is_active BOOLEAN DEFAULT true
);

CREATE UNIQUE INDEX IF NOT EXISTS providers_profile_service_key
  ON providers (profile_id, service_id);

CREATE TABLE IF NOT EXISTS bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  provider_id BIGINT REFERENCES providers(id),
  slot_time TIMESTAMP WITH TIME ZONE,
  status TEXT DEFAULT 'pending',
  total_price FLOAT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ── 2. ROW LEVEL SECURITY ─────────────────────────────────────

-- services: public read
ALTER TABLE services ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read for services" ON services;
CREATE POLICY "Allow public read for services" ON services FOR SELECT USING (true);

-- providers: public read
ALTER TABLE providers ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read for providers" ON providers;
CREATE POLICY "Allow public read for providers" ON providers FOR SELECT USING (true);

DROP POLICY IF EXISTS "Users can insert own provider profiles" ON providers;
CREATE POLICY "Users can insert own provider profiles" ON providers
  FOR INSERT WITH CHECK (auth.uid() = profile_id);

DROP POLICY IF EXISTS "Users can update own provider profiles" ON providers;
CREATE POLICY "Users can update own provider profiles" ON providers
  FOR UPDATE USING (auth.uid() = profile_id)
  WITH CHECK (auth.uid() = profile_id);

-- profiles: public read + owner can update
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read for profiles" ON profiles;
CREATE POLICY "Allow public read for profiles" ON profiles FOR SELECT USING (true);

DROP POLICY IF EXISTS "Users can update own profile" ON profiles;
CREATE POLICY "Users can update own profile" ON profiles
  FOR UPDATE USING (auth.uid() = id);

DROP POLICY IF EXISTS "Users can insert own profile" ON profiles;
CREATE POLICY "Users can insert own profile" ON profiles
  FOR INSERT WITH CHECK (auth.uid() = id);

-- bookings: owner can insert, read, and update their own rows
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can insert own bookings" ON bookings;
CREATE POLICY "Users can insert own bookings" ON bookings
  FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can read own bookings" ON bookings;
CREATE POLICY "Users can read own bookings" ON bookings
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own bookings" ON bookings;
CREATE POLICY "Users can update own bookings" ON bookings
  FOR UPDATE USING (auth.uid() = user_id);

-- ── 3. SEED DATA — SERVICES ───────────────────────────────────

INSERT INTO services (name, description, icon_name) VALUES
  ('Plumber',       'Plumbing repairs, pipe fitting, and installation',   'wrench'),
  ('Electrician',   'Electrical wiring, repairs, and installations',      'zap'),
  ('Carpenter',     'Woodwork, furniture assembly and repair',            'tool'),
  ('Painter',       'Interior and exterior painting services',            'brush'),
  ('Cleaner',       'Deep home and office cleaning',                      'sparkles'),
  ('Househelper',   'Daily chores, cooking, and house management',        'home')
ON CONFLICT (name) DO NOTHING;

-- ── 4. REVIEWS ────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id BIGINT REFERENCES bookings(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  provider_id BIGINT REFERENCES providers(id) ON DELETE CASCADE,
  rating INTEGER CHECK (rating >= 1 AND rating <= 5),
  review_text TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS reviews_booking_key
  ON reviews (booking_id);

ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read for reviews" ON reviews;
CREATE POLICY "Allow public read for reviews" ON reviews FOR SELECT USING (true);

DROP POLICY IF EXISTS "Users can insert own reviews" ON reviews;
CREATE POLICY "Users can insert own reviews" ON reviews
  FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own reviews" ON reviews;
CREATE POLICY "Users can update own reviews" ON reviews
  FOR UPDATE USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE OR REPLACE FUNCTION public.refresh_provider_rating()
RETURNS trigger AS $$
DECLARE
  target_provider_id BIGINT;
BEGIN
  target_provider_id := COALESCE(NEW.provider_id, OLD.provider_id);

  UPDATE public.providers
  SET rating = COALESCE((
    SELECT ROUND(AVG(rating)::numeric, 2)
    FROM public.reviews
    WHERE provider_id = target_provider_id
  ), 0)
  WHERE id = target_provider_id;

  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS reviews_refresh_provider_rating ON public.reviews;
CREATE TRIGGER reviews_refresh_provider_rating
  AFTER INSERT OR UPDATE OR DELETE ON public.reviews
  FOR EACH ROW EXECUTE PROCEDURE public.refresh_provider_rating();
