name: CI - Build and Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Lint Dockerfile
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: app/Dockerfile

    - name: Lint Helm Chart
      run: helm lint ./charts/web-app

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        cache-dependency-path: app/package.json

    - name: Install dependencies
      run: |
        cd app
        npm install

    - name: Run tests
      run: |
        cd app
        npm test

  build-test:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build Docker image (Test)
      run: |
        cd app
        docker build -t k8s-cicd-demo-app:${{ github.sha }} .
